name: Android Pipeline
on:
  push:
    branches:
      - main
env:
  JAVA_VERSION: 17
  ANDROID_COMPILE_SDK_VERSION: 34
  ANDROID_BUILD_TOOL: '34.0.0'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: gradle
      - name: Grant access to execute gradle
        run: chmod +x gradlew
      - name: Run lint
        run: ./gradlew lintDebug
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: gradle
      - name: Grant access to execute gradle
        run: chmod +x gradlew
      - name: Run Test
        run: ./gradlew testDebugUnitTest
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    outputs:
      version: ${{steps.set_version.outputs.version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: temurin
          cache: gradle
      - name: Grant access to execute gradle
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew assembleDebug --stacktrace
      - name: Rename Debug APK with build number
        id: set_version
        run: |
          VERSION=$(./gradlew -q printVersionName)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT   # expose as job output
          mv app/build/outputs/apk/debug/app-debug.apk \
             app/build/outputs/apk/debug/app-debug-${VERSION}-${{ github.run_number }}.apk
      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-${{env.VERSION}}-${{github.run_number}}
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 14
  upload:
    name: Upload to Firebase or Playstore
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload to Firebase
        uses: actions/download-artifact@v4
        with:
          name: debug-apk-${{needs.build.outputs.version}}-${{github.run_number}}
          path: apk/
      - name: Uploading
        run: |
          echo Pending uploading task
          echo "APK successfully distributed!"
          echo "Run:    ${{ github.run_number }}"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"

    
